namespace Biss.Mapper.Abstractions;

/// <summary>
/// Marks a class as a mapper that will have its implementation generated by the source generator.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class MapperAttribute : Attribute
{
    /// <summary>
    /// Gets or sets a value indicating whether to ignore null values during mapping.
    /// </summary>
    public bool IgnoreNullValues { get; set; } = false;

    /// <summary>
    /// Gets or sets a value indicating whether to ignore null collections during mapping.
    /// </summary>
    public bool IgnoreNullCollections { get; set; } = false;

    /// <summary>
    /// Gets or sets a value indicating whether to use deep copy for complex objects.
    /// </summary>
    public bool UseDeepCopy { get; set; } = false;
}
